DROP DATABASE IF EXISTS MYTUBE;
CREATE DATABASE MYTUBE;
USE MYTUBE;

DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS(
    USERNAME VARCHAR(15) PRIMARY KEY,
    PASSWORD VARCHAR(72) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL,
    CREATION_DATE TIMESTAMP
);

DROP TABLE IF EXISTS VIDEOS;
CREATE TABLE VIDEOS(
    VIDEO_ID INT PRIMARY KEY,
    USERNAME VARCHAR(15) NOT NULL,
    UPLOAD_DATE TIMESTAMP,
    FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME)
);

DROP TABLE IF EXISTS SUBS;
CREATE TABLE SUBS(
    USERNAME VARCHAR(15),
    SUBSCRIBED_TO VARCHAR(15),
    PRIMARY KEY (USERNAME, SUBSCRIBED_TO),
    FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME),
    FOREIGN KEY (SUBSCRIBED_TO) REFERENCES USERS(USERNAME)
);

DROP TABLE IF EXISTS MSGS;
CREATE TABLE MSGS(
    SENDER VARCHAR(15),
    RECEIVER VARCHAR(15),
    MSG VARCHAR(255),
    SEND_DATE TIMESTAMP,
    SEEN BOOLEAN,
    PRIMARY KEY (SENDER, RECEIVER, MSG, SEND_DATE),
    FOREIGN KEY (SENDER) REFERENCES USERS(USERNAME),
    FOREIGN KEY (RECEIVER) REFERENCES USERS(USERNAME)
);