CREATE
OR REPLACE DATABASE MYTUBE;

USE MYTUBE;

CREATE
OR REPLACE TABLE USERS (
    USERNAME VARCHAR(15) PRIMARY KEY,
    PASSWORD VARCHAR(72) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL,
    CREATION_DATE TIMESTAMP
);

CREATE
OR REPLACE TABLE VIDEOS (
    VIDEO_ID INT PRIMARY KEY,
    USERNAME VARCHAR(15) NOT NULL,
    UPLOAD_DATE TIMESTAMP,
    FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME)
)