<?php
include "db_connection.php";

$USERNAME = $_GET['USERNAME'];
$CHATTERLY_USERNAME = $_GET['CHATTERLY_USERNAME'];
$SET_CHATTERLY_USERNAME_QUERY = $CONN->query("UPDATE USERS SET CHATTERLY_USERNAME = '$CHATTERLY_USERNAME' WHERE USERNAME = '$USERNAME'");

$CONN->close();